# Generated by Django 5.2.1 on 2025-05-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'Javascript'), ('go', 'Goland'), ('cpp', 'C++'), ('html', 'HTML')], max_length=30),
        ),
    ]
